"use client";

import Link from "next/link";
import { ArrowLeft, Printer } from "lucide-react";

export function ReportShell({
  title,
  subtitle,
  regionLabel = "Louisville–Kentuckiana",
  children,
}: {
  title: string;
  subtitle?: string;
  regionLabel?: string;
  children: React.ReactNode;
}) {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const handlePrint = () => {
    if (typeof window !== "undefined") window.print();
  };

  return (
    <div className="min-h-screen bg-cream text-charcoal">
      {/* Toolbar — hidden on print */}
      <div className="print:hidden no-print sticky top-0 z-10 border-b border-cream-shadow bg-cream/95 backdrop-blur">
        <div className="mx-auto max-w-[900px] px-6 py-3 flex items-center justify-between">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-[12px] font-semibold text-charcoal-soft hover:text-slate-blue"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            Back to demo
          </Link>
          <button
            type="button"
            onClick={handlePrint}
            className="inline-flex items-center gap-1.5 rounded-full bg-slate-blue text-cream px-4 py-1.5 text-[11px] font-semibold uppercase tracking-[0.08em] hover:bg-slate-blue-light transition-colors"
          >
            <Printer className="w-3 h-3" />
            Print / Save PDF
          </button>
        </div>
      </div>

      {/* Report body */}
      <div className="report-page mx-auto max-w-[900px] px-6 py-10 sm:px-10 sm:py-14">
        <header className="mb-10 pb-6 border-b border-cream-shadow">
          <div className="text-[10px] font-bold uppercase tracking-[0.18em] text-slate-blue mb-3">
            Provender · A Farmer&apos;s Share Corporation
          </div>
          <h1 className="font-display text-[36px] sm:text-[42px] font-semibold leading-[1.15] text-charcoal tracking-tight">
            {title}
          </h1>
          {subtitle ? (
            <p className="mt-3 text-[16px] text-charcoal-soft leading-relaxed max-w-prose">
              {subtitle}
            </p>
          ) : null}
          <div className="mt-6 flex flex-wrap gap-x-8 gap-y-1 text-[11px] text-charcoal-soft/80 font-mono tabular-nums">
            <span>
              <b className="text-charcoal">Region:</b> {regionLabel}
            </span>
            <span>
              <b className="text-charcoal">Generated:</b> {today}
            </span>
            <span>
              <b className="text-charcoal">Source:</b> Provender demo dataset
            </span>
          </div>
        </header>

        {children}

        <footer className="mt-14 pt-6 border-t border-cream-shadow text-[10px] text-charcoal-soft/70 leading-relaxed">
          <div className="mb-2 font-semibold text-charcoal-soft">
            About this report
          </div>
          <p>
            Generated by the Provender demo at{" "}
            <span className="font-mono">prov-demo.afarmersshare.com</span>.
            Schema is production-identical; numeric values are illustrative
            for the Louisville–Kentuckiana demo region. Replace the{" "}
            <i>demo dataset</i> label with real region data to produce a
            genuine report for your region.
          </p>
          <p className="mt-2">
            © {new Date().getFullYear()} A Farmer&apos;s Share Corporation,
            PBC. Contact{" "}
            <a href="mailto:hello@afarmersshare.com" className="underline">
              hello@afarmersshare.com
            </a>{" "}
            to discuss generating this report for your region.
          </p>
        </footer>
      </div>
    </div>
  );
}

export function ReportSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="report-section mb-10">
      <h2 className="font-display text-[22px] font-semibold text-slate-blue leading-tight mb-1">
        {title}
      </h2>
      <div className="mt-4">{children}</div>
    </section>
  );
}

export function ReportLoading() {
  return (
    <div className="min-h-screen bg-cream text-charcoal flex items-center justify-center">
      <div className="text-sm text-charcoal-soft">Generating report…</div>
    </div>
  );
}
