// Seed test user accounts for persona QA.
//
// Creates eight auth.users rows via the Supabase admin API (email-confirmed,
// no magic-link loop), then calls promote_user() for each to set tier +
// persona + reseed entitlements. Idempotent: re-runs skip already-existing
// accounts and re-promote (which is itself idempotent).
//
// Run with:   node --env-file=.env.local scripts/seed_test_users.mjs
//
// Reads:
//   NEXT_PUBLIC_SUPABASE_URL
//   SUPABASE_SERVICE_ROLE_KEY
//
// Writes:
//   .test-credentials.md  — gitignored summary of email/password/tier/persona
//                           so you can log in manually any time.

import { createClient } from "@supabase/supabase-js";
import { writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE) {
  console.error(
    "Missing env. Run with: node --env-file=.env.local scripts/seed_test_users.mjs",
  );
  console.error("Need NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.");
  process.exit(1);
}

// Mirrors the suggested fixture set from sql/011_test_user_promotion.sql.
// Slug becomes the gmail-alias suffix: kelsey+farmer@afarmersshare.com etc.
const FIXTURES = [
  { slug: "farmer", tier: "farmer_paid", persona: "farmer" },
  { slug: "farmerfree", tier: "farmer_free", persona: "farmer" },
  { slug: "buyer", tier: "buyer_institutional", persona: "buyer" },
  { slug: "hub", tier: "buyer_foodhub", persona: "hub" },
  { slug: "policy", tier: "government", persona: "policymaker" },
  { slug: "nonprofit", tier: "nonprofit", persona: "nonprofit" },
  { slug: "funder", tier: "funder", persona: "funder" },
  { slug: "afs", tier: "afs_internal", persona: "afs" },
];

const EMAIL_BASE = "kelsey";
const EMAIL_DOMAIN = "afarmersshare.com";
const emailFor = (slug) => `${EMAIL_BASE}+${slug}@${EMAIL_DOMAIN}`;

// One shared password across all test accounts. Strong (32 chars, base64url)
// but written once into .test-credentials.md so Kelsey can paste it when
// logging in manually. Re-running the script reuses the existing password
// from the prior run — see readExistingPassword below — so existing
// auth.users rows don't get out of sync with the credentials file.
async function readExistingPassword() {
  try {
    const { readFile } = await import("node:fs/promises");
    const content = await readFile(".test-credentials.md", "utf8");
    const match = content.match(/Password:\s*`([^`]+)`/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

const password =
  (await readExistingPassword()) ?? randomBytes(24).toString("base64url");

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const results = [];

for (const { slug, tier, persona } of FIXTURES) {
  const email = emailFor(slug);
  let createStatus = "created";

  const { error: createErr } = await supabase.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
  });

  if (createErr) {
    if (
      createErr.message?.toLowerCase().includes("already") ||
      createErr.code === "email_exists"
    ) {
      createStatus = "exists";
    } else {
      console.error(`✗ ${email}: createUser failed —`, createErr.message);
      results.push({ slug, email, tier, persona, error: createErr.message });
      continue;
    }
  }

  const { error: promoteErr } = await supabase.rpc("promote_user", {
    p_email: email,
    p_tier: tier,
    p_persona: persona,
  });

  if (promoteErr) {
    console.error(`✗ ${email}: promote_user failed —`, promoteErr.message);
    results.push({ slug, email, tier, persona, error: promoteErr.message });
    continue;
  }

  console.log(`✓ ${email.padEnd(40)} ${createStatus.padEnd(8)} → ${tier} / ${persona}`);
  results.push({ slug, email, tier, persona, status: createStatus });
}

// Build the credentials markdown.
const ok = results.filter((r) => !r.error);
const failed = results.filter((r) => r.error);

const tableRows = ok
  .map(
    (r) =>
      `| ${r.persona} | ${r.tier} | \`${r.email}\` |`,
  )
  .join("\n");

const failedSection = failed.length
  ? `\n## Failures\n\n${failed
      .map((r) => `- \`${r.email}\` — ${r.error}`)
      .join("\n")}\n`
  : "";

const md = `# Test user credentials (local-only, gitignored)

Generated by \`scripts/seed_test_users.mjs\`. Re-run that script any time to
recreate / reseed these accounts. The script is idempotent.

**Password (shared across all test accounts):**

\`${password}\`

## Accounts

| Persona | Tier | Email |
|---|---|---|
${tableRows}
${failedSection}
## How to use

1. Open the demo in a private/incognito window so it doesn't share your real
   session: https://prov-demo.afarmersshare.com/login
2. Choose **email + password** (not Google OAuth — these accounts only have
   the password above set, no Google identity).
3. Paste the email + the password above.
4. Land on \`?persona=<their-persona>\`. The welcome strip + locked tabs
   reflect what that tier sees.

To reset / refresh entitlements at any time, re-run:

\`\`\`
node --env-file=.env.local scripts/seed_test_users.mjs
\`\`\`

To wipe all test users (e.g. before a clean re-seed), delete them from
**Supabase → Authentication → Users**, then re-run the script.
`;

await writeFile(".test-credentials.md", md, "utf8");

const okCount = ok.length;
const failedCount = failed.length;
console.log(
  `\nDone. ${okCount}/${FIXTURES.length} accounts ready. ${failedCount} failed. Credentials → .test-credentials.md`,
);

if (failedCount > 0) process.exit(1);
